version: '3.1'

services:
  mongo:
    image: mongo
    container_name: my_tracking_list-mongo
    ports:
      - "27017:27017"
    volumes:
      - ${HOME}/.docker_volume/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: my_tracking_list

  postgres:
    image: postgres
    container_name: my_tracking_list-postgres
    volumes:
      - ${HOME}/.docker_volume/postgress:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin123
      POSTGRES_PASSWORD: 123admin

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: my_tracking_list-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: admin123
      DB_SCHEMA: public
      DB_PASSWORD: 123admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
      - "8543:8443"
    depends_on:
      - postgres