version: '3.1'

services:
  mongo:
    image: mongo
    container_name: my_tracking_list-db
    ports:
      - "27017:27017"
    volumes:
      - ${HOME}/.docker_volume/mongo/my-tracking-list:/data/db
    environment:
      MONGO_INITDB_DATABASE: my_tracking_list
