version: '3.1'

services:
  mongo:
    image: mongo
    container_name: my_tracking_list-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - .docker_volume/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: my_tracking_list
