quarkus:
    mongodb:
        connection-string: ${MY_TRACKING_LIST_BACKEND_DATABASE_URL}
        database: ${MY_TRACKING_LIST_BACKEND_DATABASE_NAME}
    swagger-ui:
        always-include: true
    http:
        port: ${PORT}
        auth:
            basic: true
        cors:
            ~: true
            origins: '*'
    log:
        level: INFO
    oidc:
        client-id: backend-service
        credentials:
            secret: secret
        tls:
            verification: none
        auth-server-url: "https://localhost:8543/auth/realms/quarkus"
    keycloak:
        policy-enforcer:
            enable: true
