quarkus:
    mongodb:
        connection-string: mongodb://localhost:27017
        database: my_tracking_list
    http:
        cors:
          ~: true
          origins: ${MY_TRACKING_LIST_BACKEND_CORS_ORIGINS}
        port: ${MY_TRACKING_LIST_BACKEND_PORT}

my-tracking-list:
    oauth:
        google:
            server-url: ${MY_TRACKING_LIST_BACKEND_OAUTH_GOOGLE_SERVER_URL}
            client-id: ${MY_TRACKING_LIST_BACKEND_OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${MY_TRACKING_LIST_BACKEND_OAUTH_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${MY_TRACKING_LIST_BACKEND_OAUTH_GOOGLE_REDIRECT_URI}
    clients:
        themoviedb:
            server-url: ${MY_TRACKING_LIST_BACKEND_THE_MOVIE_DB_URL}
            api-key: ${MY_TRACKING_LIST_BACKEND_THE_MOVIE_DB_API_KEY}
